### ISSUE TITLE
When new version assets?

### ISSUE THREAD

**Issue by reiify** [umaichanuwu/StarRailTextures#1]

**Comment by umaichanuwu** [comment]
Star rail 2.1 was released just now not even a day ago, this will be updated within the next week I just need a bit of time to extract and upload all

**Comment by umaichanuwu** [comment]
This repo is a pain to maintain bc of it's size so it'll take a bit more time sowy

**Comment by reiify** [comment]
Already something, thanks for not abandoning

**Comment by umaichanuwu** [comment]
Everything uploaded <3
Make sure to check the [note](https://github.com/umaichanuwu/StarRailTextures/blob/8cf53fc421fecdc28c51102d32f16e54cc1cef47/README.md)
